config/routes.rb
Rails.application.routes.draw do
  get '/career' => "career#index"
  get '/transfer' => "transfer#index"
  post '/transfer' => "transfer#index"
  get '/news' => "news#index"
  get '/event' => "event#index"
  get '/about' => "about#index"
  get '/add_news' => "add_news#index"
  post '/add_news' => "add_news#show"

  get '/transfer/:name' => "transfer#show", as: :transfer_show
  get '/career/:name' => "career#show", as: :career_show
  get '/event/:name' => "event#show", as: :event_show
  get '/news/:id' => "news#show", as: :news_show

  get '/coming_soon' => "top#coming_soon"

  get '/login/:id' => "login#show"
  get '/login' => "login#login_form"
  post '/login' => "login#login"
  get '/registar' => "login#new"
  post '/registar' => "login#create"
  get '/logout' => "login#logout"
  
  root 'top#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  layout 'template_top.html.erb'
  
  def index
    #TOPには日時の新しいイベントから4つだけ表示する
    @events = Event.all.order(date: :desc).limit(4)
    #TOPには日時の新しいニュースから10個だけ表示する
    @news = News.all.order(date: :desc).limit(10)
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/top/coming_soon.html.erb
<% content_for :title do %>
このページは現在準備中です。
<% end %>

<div style="background-image: url(<%= asset_path('img/bg7.jpg') %>);">

  <div class="pt-5">
    <div class="pt-5">
    </div>
  </div>

  <div class="container">
    <div style="margin-top:120px;">
      <div class="col-lg-9 col-md-9 ml-auto mr-auto">
        <div class="card">
          <div class="row" style="padding: 40px;">
            <div class="col-lg-8 col-md-12 ml-auto mr-auto">
              <div style="font-size: 31px; padding-top: 30px; line-height: 1.5;">
                <b>このページは現在準備中です。<br>もうしばらくお待ちください。<br>
                <div class="link_to_top">
                  <a href="/">トップページへ戻る</a></b>
                </div>
              </div>
            </div>
            <div class="col-lg-4 col-md-12 col-xs-12 ml-auto mr-auto" style="align: center;">
              <img src=<%= asset_path('img/logo.png') %> alt="logo.png" width="200px" height="auto">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="pt-5">
    <div class="pt-5">
    </div>
  </div>

</div>

app/views/top/index.html.erb
<% content_for :title do %>
高専からの進学・就職ならWUKS(ワックス)
<% end %>

<div class="page-header header-filter clear-filter area" data-parallax="false">
  <ul class="circles">
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
  </ul>
  <div class="container">
    <div class="row">
      <div class="col-md-8 ml-auto mr-auto">
        <div class="brand">
          <h1>タチアガレ<br>高専生</h1>
          <h3>高専からの就職・進学ならWUKS(ワックス)</h3>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="container">
  <div class="contents_list text-center pad50">
    <div class="container">
      <div class="contents_introduction">
        <h2 style="font-weight: 700">全国の高専生と情報を共有しよう</h2>
        <h4>高専生の進学・就職は情報戦。沢山の情報を見つけよう。</h4>
      </div>

      <div class="row">
        <div class="col-4 main-item">
          <a href="transfer">
            <div class="card in_a">
              <div class="card-body mt-2">
                <i class="material-icons">school</i>
                <p class="pt-2"><b>編入情報</b>を探す</p>
              </div>
            </div>
          </a>
        </div>
        <div class="col-4 main-item">
          <a href="career">
            <div class="card in_a">
              <div class="card-body mt-2">
                <i class="material-icons">business</i>
                <p class="pt-2"><b>企業情報</b>を探す</p>
              </div>
            </div>
          </a>
        </div>
        <div class="col-4 main-item">
          <a href="event">
            <div class="card">
              <div class="card-body mt-2">
                <i class="material-icons">record_voice_over</i>
                <p class="pt-2"><b>イベント</b>を探す</p>
              </div>
            </div>
          </a>
        </div>
      </div>

    </div>

  </div>
  <div class ="pad_border">
  </div>

  <div class ="row">
  　<!-- イベントの方　-->
    <div class ="col-md-8">
      <!-- イベント情報を新しいものから3つ並べる -->
      <div class=content_body>
        <div class="contents_introduction">
          <h2><b>イベント情報</b></h2>
        </div>
        <div class="container">
          <div class ="row">
            <% @events.each do |events| %>
            <div class ="v2-event-list__item">
              <%= link_to event_show_path(name:events.name) do %>
              <img class="v2-event__logo lazyloaded" src = <%= asset_path("img/event/type1.jpg") %> alt="">
                <div class ="badge_span">
                  <div class ="special_badge">
                  <% if events.date > Date.today %>
                  <span class="badge badge-pill badge-warning">募集中</span>
                  <% else %>
                  <span class="badge badge-pill badge-default">応募終了</span>
                  <% end %>
                  </div>
                  <p class = "eventTags">
                  <%= events.pref %>　|　<%= events.event_type %>　|　交通費支給
                  </p>
                </div>
                <p class="eventTitle">
                <%= events.name %>
                </p>
                <p class="eventDate">
                  日時：<%= events.date.strftime("%Y年%m月%d日") %>
                </p>
                <p class="eventPlace">
                  場所：<%= events.place %>
                </p>
              <% end %>

            </div>
            <% end %>
          </div>
        </div>
        <div class = "nextArea">
          <a href="/event">
            <p class ="go_list">全てのイベントを見る
            <i class="material-icons">arrow_forward</i></p>
          </a>
        </div>
      </div>
    </div>
    <!-- お知らせの方　-->
    <div class ="col-md-3">
      <div class="content_body">
        <div class="contents_introduction">
          <h2><b>お知らせ</b></h2>
        </div>
        <div class="pad10">
        </div>
        <ul id="notic_list">
          <% @news.each do |news| %>
          <li>
            <div>
              <p class="date"><%= news.date %></p>
              <p class="title">
                <%= link_to news_show_path(id:news.id) do %>
                <%= news.name %>
                <% end %>
              </p>
            </div>
          </li>
          <% end %>
        </ul>
        <div class="nextArea">
          <a href="/news">
            <p class ="go_list">全てのお知らせを見る
            <i class="material-icons">arrow_forward</i></p>
          </a>
        </div>
      </div>
    
    </div>

  </div>

</div>

<div class ="pad50">
</div>