config/routes.rb
Rails.application.routes.draw do
  get '/career' => "career#index"
  get '/transfer' => "transfer#index"
  post '/transfer' => "transfer#index"
  get '/news' => "news#index"
  get '/event' => "event#index"
  get '/about' => "about#index"
  get '/add_news' => "add_news#index"
  post '/add_news' => "add_news#show"

  get '/transfer/:name' => "transfer#show", as: :transfer_show
  get '/career/:name' => "career#show", as: :career_show
  get '/event/:name' => "event#show", as: :event_show
  get '/news/:id' => "news#show", as: :news_show

  get '/coming_soon' => "top#coming_soon"

  get '/login/:id' => "login#show"
  get '/login' => "login#login_form"
  post '/login' => "login#login"
  get '/registar' => "login#new"
  post '/registar' => "login#create"
  get '/logout' => "login#logout"
  
  root 'top#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/career_controller.rb
class CareerController < ApplicationController
  layout 'template_listpage.html.erb'
  
  def index
    @comps = Comp.all
    @areas = ['化学系','土木・建築系','電気系','機械系','情報系','学科不問']
  end

  def show
    @comp = Comp.find_by!(name: params[:name])
    @areas = ['化学系','土木・建築系','電気系','機械系','情報系','学科不問']
  end
end

app/helpers/career_helper.rb
module CareerHelper
end

app/views/career/index.html.erb
<% content_for :title do %>
就職 | WUKS
<% end %>

<section class="py-5 bg-image-full" style="background-image: url(<%= asset_path('img/profile_city.jpg') %>);">
  <div style="height: 150px;">
    <div class="pt-5">
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto">
          <div class="brand">
            <h1>企業情報一覧</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

 <div class="container">
  <div class="row">
    <% @comps.each do |comps| %>
      <div class="col-md-3 col-sm-6" style="margin-bottom: 15px;">
        <%= link_to career_show_path(name:comps.name) do %>
          <div class="card" id="career" style="height: 90%; margin-bottom: 0px;">
            <div class="listImg">
              <img src=<%= asset_path("img/comp/#{comps.name.gsub(" ", "")}_logo.jpg") %> alt="">
            </div>
            <div class="listContent">
              <div class="listTitle">
                <%= comps.name %>
              </div>
              <div class="contentDetail">
              </div>
              <div class="tagArea">
                <span class="badge badge-pill badge-rose"><%= comps.place %></span>
                <% 6.times do |i| %>
                  <% if comps.area[i] == 1 %>
                    <span class="badge badge-pill badge-success"><%= @areas[i] %></span>
                  <% end %>
                <% end %>
                <span class="badge badge-pill badge-info"><%= comps.scale %></span>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>   

  </div>
 </div>

app/views/career/show.html.erb
<% content_for :title do %>
<%= @comp.name %> | 就職
<% end %>

<section class="py-5 bg-image-full"
  style="background-image: url(<%= asset_path("img/comp/#{@comp.name.gsub(" ", "")}_back.jpg") %>);">
  <div style="height: 150px;"></div>
</section>

<div class="spEntry sp">
  <div class="joinButton">
    <a target="_blank" href="<%= @comp.url %>">もっと詳しく見る</a>
  </div>
</div>

<div class="container">
  <div class="row" style="margin-top: 15px;">
    <div class="col-md-9 padding-res-comp">
      <div class="card-header card-header-primary">
        <div class="container pt-3">
          <% unless @comp.has_original_format?%>
          <h3 class="sub">ミッション</h3>
          <%= simple_format(@comp.mission, {}, wrapper_tag: "div class='article' id='mission'") %>
<!--

          <div class="card card-raised card-carousel">
              <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="3000">
                <ol class="carousel-indicators">
                  <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                  <li data-target="#carouselExampleIndicators" data-slide-to="1" class=""></li>
                  <li data-target="#carouselExampleIndicators" data-slide-to="2" class=""></li>
                </ol>
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img class="d-block w-100" src= "img/comp/雨宮天.png" %>  alt="First slide">
                    <div class="carousel-caption d-none d-md-block">
                      <h4>
                        Yellowstone National Park, United States
                      </h4>
                    </div>
                  </div>
                  <div class="carousel-item">
                    <img class="d-block w-100" src="img/comp/雨宮天2.jpg" %>  alt="Second slide">
                    <div class="carousel-caption d-none d-md-block">
                      <h4>
                        Somewhere Beyond, United States
                      </h4>
                    </div>
                  </div>
                  <div class="carousel-item">
                    <img class="d-block w-100" src="img/comp/雨宮天3.jpg" %>  alt="Third slide">
                    <div class="carousel-caption d-none d-md-block">
                      <h4>
                        Yellowstone National Park, United States
                      </h4>
                    </div>
                  </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                  <i class="material-icons">keyboard_arrow_left</i>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                  <i class="material-icons">keyboard_arrow_right</i>
                  <span class="sr-only">Next</span>
                </a>
              </div>
          </div>

-->
          <div class ="pt-5"></div>

          <h3 class="sub">なにをやっているのか</h3>
          <%= simple_format(@comp.what, {}, wrapper_tag: "div class='article'") %>
          <h3 class="sub">職種</h3>
          <%= simple_format(@comp.occupation, {}, wrapper_tag: "div class='article'") %>
          <h3 class="sub">求める人材</h3>
          <%= simple_format(@comp.want, {}, wrapper_tag: "div class='article'") %>
          <h3 class="sub">高専生・高専卒に一言</h3>
          <%= simple_format(@comp.comment, {}, wrapper_tag: "div class='article'") %>

          <% else %>
          <%= simple_format(@comp.original_text, {}, wrapper_tag: "div", sanitize: false) %>

          <% end %>
          <div class="detail-button text-center padding-res">
            <a id="center" href=<%= @comp.url %> target="_blank">
              <button class="btn btn-primary btn-lg">もっと詳しく見る
                <div class="ripple-container"></div>
              </button>
            </a>
            <div class="pt-5"></div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-3 padding-res-comp">
      <div class="card-header card-header-primary sticky">
        <div class="container pt-3">
          <h4 class="comp-rel">
            会社情報
          </h4>
          <a class="company-title-section" href="<%= @comp.url %>" id="company-info-section">
            <img src=<%= asset_path("img/comp/#{@comp.name.gsub(" ", "")}_logo.jpg") %> alt="" width="56" height="56"
              class="company-avatar lazy">
            <div class="company-name">
              <%= @comp.name %>
            </div>
          </a>

          <ul class="comp-info-list">
            <li>
              <i class="material-icons">flag</i> <%= @comp.founded_year %>/<%= @comp.founded_month %> に設立<br>
            </li>
            <li>
              <i class="material-icons">people</i> <%= @comp.employees %>人のメンバー<br>
            </li>
            <li>
              <i class="material-icons">place</i>
              <a href="http://maps.google.co.jp/maps/search/+<%= @comp.address %>"
                target="_blank"><u><%= @comp.address %></u></a><br>
              </a>
            </li>
            <div class="place pt-3">
              <div class="map-container">
                <iframe class="iframe-wrap"
                  src="https://maps.google.co.jp/maps?output=embed&q=<%= @comp.address %>&z=14" width="400" height="300" frameborder="0" scrolling="no" ></iframe>
              </div>
            </div>
          </ul>

        </div>

      </div>
    </div>


  </div>
</div>


<div class="padding-res"></div>

app/views/career/top.html.erb
<h1>Career#top</h1>
<p>Find me in app/views/career/top.html.erb</p>