config/routes.rb
Rails.application.routes.draw do
  get '/career' => "career#index"
  get '/transfer' => "transfer#index"
  post '/transfer' => "transfer#index"
  get '/news' => "news#index"
  get '/event' => "event#index"
  get '/about' => "about#index"
  get '/add_news' => "add_news#index"
  post '/add_news' => "add_news#show"

  get '/transfer/:name' => "transfer#show", as: :transfer_show
  get '/career/:name' => "career#show", as: :career_show
  get '/event/:name' => "event#show", as: :event_show
  get '/news/:id' => "news#show", as: :news_show

  get '/coming_soon' => "top#coming_soon"

  get '/login/:id' => "login#show"
  get '/login' => "login#login_form"
  post '/login' => "login#login"
  get '/registar' => "login#new"
  post '/registar' => "login#create"
  get '/logout' => "login#logout"
  
  root 'top#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/add_news_controller.rb
class AddNewsController < ApplicationController
  layout 'template_listpage.html.erb'
  
  def index
    @news = News.all.order(date: :desc)
  end

  def show 
    @news_name = params[:title]
    upload_file = params[:upload]
    @news_content = if !upload_file.nil?
      upload_file.read.force_encoding("UTF-8")
    else
      nil
    end
    @dummy = params[:dummy] != "0"

    
    if !params[:preview]
      case params[:upload_type]
      when "new"
        if !@news_content.nil?
          News.create(name: @news_name, content: @news_content, date: Date.today)
          redirect_to action: :index
        else
          redirect_to action: :index, notice: "ファイルを指定してください"
        end
      when "upload"
        news = News.find_by(id: params[:news_id].to_i)
        news.inspect
        if !@news_content.nil?
          news.update(name: @news_name, content: @news_content, date: Date.today)
        else
          news.update!(name: @news_name, date: Date.today)
        end
        redirect_to action: :index
      when "disable"
        news = News.find_by(id: params[:news_id].to_i)
        news.destroy
        redirect_to action: :index
      end
    elsif @news_content.nil?
      redirect_to action: :index, notice: "ファイルを指定してください"
    end
  end

end

app/views/add_news/index.html.erb
<% content_for :title do %>
ニュース追加
<% end %>

<section class="py-5 bg-image-full" style="background-image: url(<%= asset_path('img/bg_news.jpg') %>);">
  <div style="height: 150px;">
    <div class="pt-5">
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto">
          <div class="brand">
            <h2 class="forbadge">
              <h2><b>新規ニュース</b></h2>
            </h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="container pt-3">

  <% if params[:notice]%>
    <p><%= params[:notice] %></p>
  <% end %>
  
  <%= form_with(url: add_news_path, multipart: true) do |f| %>
    <div>
      タイトル：<%= f.text_field :title %>
    </div>
    <div>
      <%= f.file_field :upload %>
    </div>
    <label>
      <%= f.check_box :dummy, {:checked => true, :autocomplete => 'off'}%>ダミー画像を表示する
    </label>
    <div class="action">
      <%= f.submit "プレビュー", name: "preview", formtarget: "_blank" %>
    </div>
    <br />
    <br />
    <div class="btn-group form-group col-md-3" data-toggle="buttons">
      <label class="btn btn-dark btn-sm active">
        <%= f.radio_button :upload_type, "new", {:checked => true, :autocomplete => "off"}%>新規
      </label>
      <label class="btn btn-dark btn-sm">
        <%= f.radio_button :upload_type, "upload", {:autocomplete => "off"}%>更新
      </label>
      <label class="btn btn-dark btn-sm">
        <%= f.radio_button :upload_type, "disable", {:autocomplete => "off"}%>削除
      </label>
    </div>
    <div class="action">
      <%= f.submit "決定" %>
    </div>
    <div>
      <% @news.each_with_index do |news, index| %>
        <%= f.radio_button :news_id, news.id, {:checked => index == 0, :autocomplete => "off"}%> <%= news.name%> <br/>
      <% end %>
    </div>
  <% end %>
</div>

app/views/add_news/show.html.erb
<% content_for :title do %>
<%= @news_name %> | お知らせ
<% end %>

<section class="py-5 bg-image-full" style="background-image: url(<%= asset_path('img/bg_news.jpg') %>);">
  <div style="height: 150px;">
    <div class="pt-5">
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto">
          <div class="brand">
            <h2 class="forbadge">
              <h2><b><%= @news_name %></b></h2>
            </h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="container main-content">
  <div class="pt-5">
    <div class="row">
      <div class="container">
        <div class="card-header card-header-primary">
          <div id="newshead">
            <p class="date">2020-02-28</p>
            <h3><%= @news_name %></h3>
          </div>
          <div id="newsbody">
            <%=
              raw @news_content.gsub(/src=.*?"([^"]+)"/) {
                'src="' + asset_path(@dummy? "img/news/Dummy.png":$1) + '"'
              }.gsub(/<%=.*?render.*?'([^']+)'.*?,.*?key.*?:.*?'([^']+)'.*?>/) {
                render $1, key: $2
              } 
            %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>