config/routes.rb
Rails.application.routes.draw do
  get '/career' => "career#index"
  get '/transfer' => "transfer#index"
  post '/transfer' => "transfer#index"
  get '/news' => "news#index"
  get '/event' => "event#index"
  get '/about' => "about#index"
  get '/add_news' => "add_news#index"
  post '/add_news' => "add_news#show"

  get '/transfer/:name' => "transfer#show", as: :transfer_show
  get '/career/:name' => "career#show", as: :career_show
  get '/event/:name' => "event#show", as: :event_show
  get '/news/:id' => "news#show", as: :news_show

  get '/coming_soon' => "top#coming_soon"

  get '/login/:id' => "login#show"
  get '/login' => "login#login_form"
  post '/login' => "login#login"
  get '/registar' => "login#new"
  post '/registar' => "login#create"
  get '/logout' => "login#logout"
  
  root 'top#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/transfer_controller.rb
class TransferController < ApplicationController
  layout 'template_listpage.html.erb'
  
  Attributes = [
    ["examtypes", "0"],
    ["otherFac", "0"],

    ["hokkaido", "1"],
    ["tohoku", "1"],
    ["hokuriku", "1"],
    ["chubu", "1"],
    ["kanto", "1"],
    ["kinki", "1"],
    ["chugoku", "1"],
    ["sikoku", "1"],
    ["kyushu", "1"],

    ["math", "1"],
    ["english", "1"],
    ["physics", "1"],
    ["chemistry", "1"],
    ["special", "1"],
    ["external_english", "1"],
    ["other_subject", "1"],

    ["engineering", "1"],
    ["science_and_engineering", "1"],
    ["science", "1"],
    ["economics", "1"],
    ["law", "1"],
    ["literature", "1"],
    ["other_faculty_type", "1"],

    ["order_by", "id"],
    ["order", "ASC"]
  ]

  def index

    @departments = Department.filter(params)
    @facluties = Faculty.filter(params, @departments)
    @univs = Univ.filter(params, @facluties, @departments)

    @filtered = Attributes.map{|attribute, default| !(params[attribute].nil? || params[attribute] == default)}.any?
  end

  def show
    @univ = Univ.find_by!(name: params[:name])
    @faculties = Faculty.where(s_name: params[:name])
  end
end

app/helpers/transfer_helper.rb
module TransferHelper
end

app/views/transfer/_badge_checkbox.html.erb
<label 
  class="badge badge-pill label-checkbox 
    <%if checked %>
      <%= badge_class %>
    <%else%>
      badge-secondary
    <%end%>" 
  id=<%= id %>
>
  <%= form.check_box(name, {
    :checked => checked, 
    :autocomplete => 'off', 
    :onChange => ("handleChangeBadge(event,'#" + id + "','" + badge_class + "')").html_safe,
    :class => 'button-checkbox'
  })%>
    <%= badge_text %>
</label>

app/views/transfer/index.html.erb
<% content_for :title do %>
進学 | WUKS
<% end %>

<section class="py-5 bg-image-full" style="background-image: url(<%= asset_path('img/bg_univ.jpg') %>);">
  <div style="height: 150px;">
    <div class="pt-5">
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto">
          <div class="brand">
            <h1>大学一覧</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<div class="container">
  <div class="pt-3">

  <div class ="pt-3">
  <% if @univs.length <= 0 %>
    <h2>条件に合致する大学はありません</h2>
  <% end %>

  <div class="row">
    <div class="col-md-3">
        <%= form_with(url: transfer_path) do |form| %>
          <h3 class="filter-type">表示条件</h3>
          <%= render :partial => "badge_checkbox", :locals => { 
            name: 'examtypes', badge_text: '推薦入試あり', badge_class: 'badge-info', id: 'labelExamTypes', checked: (params['examtypes'] == '1'), form: form
          } %>
          <%= render :partial => "badge_checkbox", :locals => { 
            name: 'otherFac', badge_text: '工学系以外も編入可', badge_class: 'badge-warning', id: 'labelOtherFac', checked: (params['otherFac'] == '1'), form: form
          } %>
          <br/>
          <hr/>
          <h3 class="filter-type">表示地域</h3>
          <%= render :partial => "badge_checkbox", :locals => { 
            name: 'hokkaido', badge_text: '北海道', badge_class: 'badge-rose', id: 'labelHokkaido', checked: !(params['hokkaido'] == '0'), form: form
          } %>
          <%= render :partial => "badge_checkbox", :locals => { 
            name: 'tohoku', badge_text: '東北', badge_class: 'badge-rose', id: 'labelTohoku', checked: !(params['tohoku'] == '0'), form: form
          } %>
          <%= render :partial => "badge_checkbox", :locals => { 
            name: 'hokuriku', badge_text: '北陸', badge_class: 'badge-rose', id: 'labelHokuriku', checked: !(params['hokuriku'] == '0'), form: form
          } %>
          <%= render :partial => "badge_checkbox", :locals => { 
            name: 'kanto', badge_text: '関東', badge_class: 'badge-rose', id: 'labelKanto', checked: !(params['kanto'] == '0'), form: form
          } %>
          <%= render :partial => "badge_checkbox", :locals => { 
            name: 'chubu', badge_text: '中部', badge_class: 'badge-rose', id: 'labelChubu', checked: !(params['chubu'] == '0'), form: form
          } %>
          <%= render :partial => "badge_checkbox", :locals => { 
            name: 'kinki', badge_text: '近畿', badge_class: 'badge-rose', id: 'labelKinki', checked: !(params['kinki'] == '0'), form: form
          } %>
          <%= render :partial => "badge_checkbox", :locals => { 
            name: 'chugoku', badge_text: '中国', badge_class: 'badge-rose', id: 'labelChugoku', checked: !(params['chugoku'] == '0'), form: form
          } %>
          <%= render :partial => "badge_checkbox", :locals => { 
            name: 'sikoku', badge_text: '四国', badge_class: 'badge-rose', id: 'labelSikoku', checked: !(params['sikoku'] == '0'), form: form
          } %>
          <%= render :partial => "badge_checkbox", :locals => { 
            name: 'kyushu', badge_text: '九州', badge_class: 'badge-rose', id: 'labelKyushu', checked: !(params['kyushu'] == '0'), form: form
          } %>
          <br />
          <hr/>
          <h3 class="filter-type">科目
            <button type="button" class="btn btn-fab btn-fab-mini btn-round" data-toggle="modal" data-target="#subjectHelpModal">
              <i class="material-icons">help_outline</i>
            </button>
          </h3>
          <div class="modal fade" id="subjectHelpModal" tabindex="-1" role="">
            <div class="modal-dialog modal-lg">
              <div class="modal-content">
                <div class="modal-body">
                  <p>選択した科目のみで構成される大学の学部学科が表示されます。</p>
                  <p>その他には「生物」、「国語」、「小論文」、「総合問題」、「実技」が含まれます。</p>
                </div>
              </div>
            </div>
          </div>
          
          <%= render :partial => "badge_checkbox", :locals => { 
            name: 'math', badge_text: '数学', badge_class: 'badge-rose', id: 'labelMath', checked: !(params['math'] == '0'), form: form
          } %>
          <%= render :partial => "badge_checkbox", :locals => { 
            name: 'english', badge_text: '英語', badge_class: 'badge-rose', id: 'labelEnglish', checked: !(params['english'] == '0'), form: form
          } %>
          <%= render :partial => "badge_checkbox", :locals => { 
            name: 'physics', badge_text: '物理', badge_class: 'badge-rose', id: 'labelPhysics', checked: !(params['physics'] == '0'), form: form
          } %>
          <%= render :partial => "badge_checkbox", :locals => { 
            name: 'chemistry', badge_text: '化学', badge_class: 'badge-rose', id: 'labelChemistry', checked: !(params['chemistry'] == '0'), form: form
          } %>
          <%= render :partial => "badge_checkbox", :locals => {
            name: 'special', badge_text: '専門', badge_class: 'badge-rose', id: 'labelSpecial', checked: !(params['special'] == '0'), form: form
          } %>
          <%= render :partial => "badge_checkbox", :locals => { 
            name: 'external_english', badge_text: '英語(外部試験)', badge_class: 'badge-rose', id: 'labelExternalEnglish', checked: !(params['external_english'] == '0'), form: form
          } %>
          <%= render :partial => "badge_checkbox", :locals => {
            name: 'other_subject', badge_text: 'その他', badge_class: 'badge-rose', id: 'labelOtherSubject', checked: !(params['other_subject'] == '0'), form: form
          } %>
          <br />
          <hr/>

          <h3 class="filter-type">学部</h3>

          <%= render :partial => "badge_checkbox", :locals => { 
            name: 'engineering', badge_text: '工学系', badge_class: 'badge-rose', id: 'labelEngineering', checked: !(params['engineering'] == '0'), form: form
          } %>
          <%= render :partial => "badge_checkbox", :locals => { 
            name: 'science_and_engineering', badge_text: '理工学系', badge_class: 'badge-rose', id: 'labelScienceAndEngineering', checked: !(params['science_and_engineering'] == '0'), form: form
          } %>
          <%= render :partial => "badge_checkbox", :locals => { 
            name: 'science', badge_text: '理学系', badge_class: 'badge-rose', id: 'labelScience', checked: !(params['science'] == '0'), form: form
          } %>
          <%= render :partial => "badge_checkbox", :locals => { 
            name: 'economics', badge_text: '経済学系', badge_class: 'badge-rose', id: 'labelEconomics', checked: !(params['economics'] == '0'), form: form
          } %>
          <%= render :partial => "badge_checkbox", :locals => {
            name: 'law', badge_text: '法学系', badge_class: 'badge-rose', id: 'labelLaw', checked: !(params['law'] == '0'), form: form
          } %>
          <%= render :partial => "badge_checkbox", :locals => { 
            name: 'literature', badge_text: '文学系', badge_class: 'badge-rose', id: 'labelLiterature', checked: !(params['literature'] == '0'), form: form
          } %>
          <%= render :partial => "badge_checkbox", :locals => { 
            name: 'other_faculty_type', badge_text: 'その他', badge_class: 'badge-rose', id: 'labelOtherFacultyType', checked: !(params['other_faculty_type'] == '0'), form: form
          } %>
          <br />
          <hr/>
          <h3 class="filter-type">並び替え</h3>
          <div class="form-row">
            <div class="form-group col-md-3">
              <%= form.select :order_by, [["デフォルト", "id"], ["試験日", "date_number"], ["名前", "rubi"]], {:selected => params["order_by"]?params["order_by"]:"id"}, {:class => "form-control"}%>
            </div>
            <div class="btn-group form-group col-md-3" data-toggle="buttons">
              <label class="btn btn-dark btn-sm <% if !(params["order"] == "DESC")%>active<% end %>">
                <%= form.radio_button :order, "ASC", {:checked => !(params["order"] == "DESC"), :autocomplete => "off", :class => "radio-order"}%>昇順
              </label>
              <label class="btn btn-dark btn-sm <% if (params["order"] == "DESC")%>active<% end %>">
                <%= form.radio_button :order, "DESC", {:checked => (params["order"] == "DESC"), :autocomplete => "off", :class => "radio-order"}%>降順
              </label>
            </div>
            
          </div>
          <input type="submit" value="絞り込む" class="btn btn-success btn">
          <!-- <input type="submit" value="デフォルトに戻す" class="btn btn-danger btn-default"> -->
        <% end %>
    </div>
    <div class="col-md-9 pad-zero">
      <% @univs.each do |univs| %>
      <div class="univ-parent">
        <!--<a href ="/transfer/<%= univs.name %>"> -->
        <div class="product border container">
          <%= link_to transfer_show_path(name:univs.name) do %>
            <div class="row">
              <div class="col-md-4">
                <img src=<%= asset_path("img/univ/#{univs.name}.jpg") %> alt="url('/assets/img/bg7.jpg');" class="img-thumbnail">
              </div>
              <div class="col-md-8">
                <h2 class="nameUni"><%= univs.name %></h2>
                <h4 class="forbadge"><span class="badge badge-pill badge-rose"><%= univs.location %></span></h4>
                <% if univs.examtypes == 1 %>
                  <h4 class="forbadge"><span class="badge badge-pill badge-success"><%= univs.date_general %></span>
                    <span class="badge badge-pill badge-success"><%= univs.date_recommend %></span>
                    <span class="badge badge-pill badge-info">推薦入試あり</span>
                <% elsif  univs.examtypes == 2 %>
                  <h4 class="forbadge"><span class="badge badge-pill badge-success"><%= univs.date_recommend %></span>
                  <span class="badge badge-pill badge-info">推薦入試のみ</span>
                <% else %>
                  <h4 class="forbadge"><span class="badge badge-pill badge-success"><%= univs.date_general %></span>
                <% end %>
                    <% if univs.otherFac == 1%>
                    <span class="badge badge-pill badge-warning">工学系以外も編入可</span>
                    <% end %>
                  </h4>
              </div>
            </div>
          <% end %>
          <div class="faculty-show" data-toggle="collapse" data-target="#collapseUniv<%= univs.id %>" aria-expanded="true" aria-controls="collapseUniv<%= univs.id %>">
            <i class="material-icons expand-mark">expand_more</i>
          </div>
          <div class="faculties-area collapse" id="collapseUniv<%= univs.id %>">
            <% @facluties.select{|facluty| facluty.s_name == univs.name}.each do |facluty| %>
              <div class="faculty-area" data-toggle="collapse" data-target="#collapseUniv<%= univs.id %>_<%= facluty.id %>" aria-expanded="true" aria-controls="collapseUniv<%= univs.id %>_<%= facluty.id %>">
                <h4 class="faculty-title">
                  <%= facluty.f_name %>
                  <i class="material-icons expand-mark-faculty">expand_more</i>
                </h4>
                <div class="collapse" id="collapseUniv<%= univs.id %>_<%= facluty.id %>">
                  <ul class ="dep_L">
                    <% @departments.select{|department| department.univ_name == univs.name && department.faculty_name == facluty.f_name}.each do |department| %>
                      <li><%= department.name %> <br/>
                        <p class = "subjects">
                          <% if department.math %>
                            数学
                          <% end %>
                          <% if department.english %>
                            英語
                          <% end %>
                          <% if department.physics %>
                            物理
                          <% end %>
                          <% if department.chemistry %>
                            化学
                          <% end %>
                          <% if department.special %>
                            専門
                          <% end %>
                          <% if department.external_english %>
                            英語(外部)
                          <% end %>
                          <% if department.interview %>
                            面接
                          <% end %>
                          <% if department.paper || department.integration || department.practical || department.biology %>
                            その他
                          <% end %>
                        </p>
                      </li>
                    <% end %>
                  </ul>
                </div>
              </div>
            <% end %>
          </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</div>

  <script>
    const handleChangeBadge = (e,id,cl) => $(id).toggleClass("badge-secondary",!e.target.checked).toggleClass(cl,e.target.checked)
    jQuery($ => {
      $('.faculty-area').on('click', function(){
        $(this).find('i').toggleClass('open')
      })
      $('.faculty-show').on('click', function(){
        $(this).find('i').toggleClass('open')
      })
    })
  </script>
</div>
</div>
<div class = "pt-5"></div>

app/views/transfer/show.html.erb
<% content_for :title do %>
<%= @univ.name %> | 進学
<% end %>

<section class="py-5 bg-image-full" style="background-image: url(<%= asset_path("img/univ/#{@univ.name}.jpg") %>);">
  <div style="height: 150px;">
    <div class="pt-5">
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto">
          <div class="brand">
            <h1><%= @univ.name %></h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<h2 class="heading">募集学部</h2>
<div class="row">
  <div class="container">
    <div class="card-header">
      <!-- Card Start -->
      <div class="card card-nav-tabs card-plain">
        <!-- Card Headder -->
        <div class="card-header card-header-primary">
          <div class="nav-tabs-navigation">
            <div class="nav-tabs-wrapper">
              <ul class="nav nav-tabs" data-tabs="tabs">
                <% @count = 0 %>
                <% @faculties.each do |faculty| %>
                <li class="nav-item">
                  <% if @count == 0%>
                  <a class="nav-link active" href="#<%= faculty.f_name %>"
                    data-toggle="tab"><%= faculty.f_name %></a>
                  <% else %>
                  <a class="nav-link" href="#<%= faculty.f_name %>" data-toggle="tab"><%= faculty.f_name %></a>
                  <% end %>
                </li>
                <% @count = @count + 1 %>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
        <!-- Card Headder End -->

        <!-- Card Main Start -->
        <div class="card-body">
          <div class="tab-content univ-padding">
            <% @count = 0 %>
            <% @faculties.each do |faculty| %>
            <% if @count == 0 %>
            <div class="tab-pane active" id="<%= faculty.f_name %>">
              <% if faculty.note == "R2" %>
                <p>※R3年度編入学の募集要項がまだ出ていないため、R2年度の情報を掲載しています。</p>
              <% end %>
              <h3 class="sub">試験時期</h3>
              <ul>
                <% if faculty.is_there_recomend %>
                <li>　推薦入試：<%= faculty.date_recomend %></li>
                <% end %>
                <% if faculty.is_there_general %>
                <li>　一般入試：<%= faculty.date_general %></li>
                <% end %>
              </ul>
              <h3 class="sub">合格発表</h3>
              <ul>
                <% if faculty.is_there_recomend %>
                <li>　推薦入試：<%= faculty.date_recomend_pass %></li>
                <% end %>
                <% if faculty.is_there_general %>
                <li>　一般入試：<%= faculty.date_general_pass %></li>
                <% end %>
              </ul>
              <h3 class="sub">募集学科</h3>
              <% array_department = faculty.department.split(",") %>
              <ul class ="dep_L">
                <% array_department.each do |department| %>
                <li><%= department %></li>
                <% end %>
              </ul>
              <div class="text-center">
                <a target="_blank" href= "<%= faculty.url %>">
                  <button class="btn btn-primary">もっと詳しく見る
                    <div class="ripple-container"></div>
                  </button>
                </a>
              </div>
            </div>
            <% else %>
            <div class="tab-pane" id="<%= faculty.f_name %>">
              <% if faculty.note == "R2" %>
                <p>※R3年度編入学の募集要項がまだ出ていないため、R2年度の情報を掲載しています。</p>
              <% end %>
              <h3 class="sub">試験時期</h3>
              <ul>
                <% if faculty.is_there_recomend %>
                <li>　推薦入試：<%= faculty.date_recomend %> </li>
                <% end %>
                <% if faculty.is_there_general %>
                <li>　一般入試：<%= faculty.date_general %></li>
                <% end %>
              </ul>
              <h3 class="sub">合格発表</h3>
              <ul class>
                <% if faculty.is_there_recomend %>
                <li>　推薦入試：<%= faculty.date_recomend_pass %></li>
                <% end %>
                <% if faculty.is_there_general %>
                <li>　一般入試：<%= faculty.date_general_pass %></li>
                <% end %>
              </ul>
              <h3 class="sub">募集学科</h3>
              <% array_department = faculty.department.split(",") %>
              <ul class = "dep_L">
                <% array_department.each do |department| %>
                <li><%= department %></li>
                <% end %>
              </ul>
              <div class="text-center">
                <a href= "<%= faculty.url %>">
                  <button class="btn btn-primary">もっと詳しく見る
                    <div class="ripple-container"></div>
                  </button>
                </a>
              </div>
            </div>
            <% end %>
            <% @count = @count + 1 %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<div class = "padding-res"></div>

app/views/transfer/top.html.erb
<section class="py-5 bg-image-full" style="background-image: url('./assets/img/bg7.jpg');">
    <div style="height: 150px;">
    <div class="container">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto">
          <div class="brand">
            <h1>編入可能大学一覧</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<div class ="container">
  
  <a href ="#">
  <div class="row product mt-5 border">
    <div class="col-md-4">
      <img src="assets/img/univ/tokyo_univ.jpg" alt="" class="img-thumbnail">
    </div>
    <div class="col-md-8">
      <h2>東京大学</h2>
      <p>編入難易度</p>
    </div>
  </div>
  </a>

  <a href ="#">
  <div class="row product border">
    <div class="col-md-4">
      <img src="assets/img/univ/tokyo_tech.jpg" alt="" class="img-thumbnail">
    </div>
    <div class="col-md-8">
      <h2>東京工業大学</h2>
      <p>編入難易度</p>
    </div>
  </div>
  </a>

  <a href ="#">
  <div class="row product border">
    <div class="col-md-4">
      <img src="assets/img/univ/kyushu_univ.jpg" alt="" class="img-thumbnail">
    </div>
    <div class="col-md-8">
      <h2>九州大学</h2>
      <p>編入難易度</p>
    </div>
  </div>
  </a>

  <a href ="#">
  <div class="row product border">
    <div class="col-md-4">
      <img src="assets/img/univ/nagoya_univ.jpg" alt="" class="img-thumbnail">
    </div>
    <div class="col-md-8">
      <h2>名古屋大学</h2>
      <p>編入難易度</p>
    </div>
  </div>
  </a>
</div>